plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.tronautils'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.tronautils"
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    // No external dependencies required
}
